
name: artmoo
version: '1.0.0'
summary: A telnet/websocket text-only Multi-user Object Orientated (MOO) server
description: |
  ArtMOO is a modern, real-time multi-user text only server with extensions
  specifically designed for artists and creatives that want to experiment
  with crossing between the virtual world and real world, however it is a
  solid base for designing any virtual world, including games.

  You can create rich interactive worlds that visitors can log into remotely
  from anywhere in the world and communicate with each other as though
  they're sitting in the same room.

grade: devel
confinement: devmode
base: core18

parts:
  artmoo:
    plugin: cmake
    source: https://github.com/bigfug/moo.git

apps:
  artmoo-daemon:
    command: bin/artmoo-daemon
  artmoo-server:
    command: bin/artmoo-server
