
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: artmoo
  version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
  summary: A telnet/websocket text-only Multi-user Object Orientated (MOO) server
  description: |
    This is my-snap's description. You have a paragraph or two to tell the
    most important story about your snap. Keep it under 100 words though,
    we live in tweetspace and your description wants to look good in the snap
    store.

    ArtMOO is a modern, real-time multi-user text only server with extensions
    specifically designed for artists and creatives that want to experiment
    with crossing between the virtual world and real world, however it is a
    solid base for designing any virtual world, including games.
    
    You can create rich interactive worlds that visitors can log into remotely
    from anywhere in the world and communicate with each other as though
    they're sitting in the same room.

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    artmoo-daemon:
      plugin: cmake
      slots:
      - network
      - network-bind
      - serial-port
    artmoo-server:
      plugin: cmake
      slots:
      - network
      - network-bind
      - serial-port

  apps:
     artmoo-daemon:
      command: artmoo-daemon
     artmoo-server:
      command: artmoo-server
 