
name: artmoo
version: '1.0.0'
summary: A telnet/websocket text-only Multi-user Object Orientated (MOO) server
description: |
  ArtMOO is a modern, real-time multi-user text only server with extensions
  specifically designed for artists and creatives that want to experiment
  with crossing between the virtual world and real world, however it is a
  solid base for designing any virtual world, including games.

  You can create rich interactive worlds that visitors can log into remotely
  from anywhere in the world and communicate with each other as though
  they're sitting in the same room.

grade: devel
confinement: devmode
base: core18
architectures:
  - build-on: [ amd64, armhf ]
  
parts:
  artmoo:
    plugin: cmake
    source: https://github.com/bigfug/moo.git
    build-snaps:
      - kde-frameworks-5-core18-sdk
      - kde-frameworks-5-core18
    configflags:
      - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DENABLE_TESTING=OFF"
      - "-DBUILD_TESTING=OFF"
      - "-DKDE_SKIP_TEST_SETTINGS=ON"
      
apps:
  artmoo-daemon:
    command: bin/artmoo-daemon
    extensions:
      - kde-neon
    plugs:
      - kde-frameworks-5-plug
      - home
      - network
      - network-bind
  artmoo-server:
    command: bin/artmoo-server
    extensions:
      - kde-neon
    plugs:
      - kde-frameworks-5-plug
      - home
      - opengl
      - network
      - network-bind
      
